//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using System.Diagnostics.CodeAnalysis;
    
    internal static unsafe partial class libcef
    {
        public const string CEF_VERSION = "118.1.1+gd6ce292+chromium-118.0.5993.32";
        public const int CEF_VERSION_MAJOR = 118;
        public const int CEF_COMMIT_NUMBER = 2835;
        public const string CEF_COMMIT_HASH = "d6ce292260a551bd69552072b41628b54e389661";
        
        public const int CHROME_VERSION_MAJOR = 118;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 5993;
        public const int CHROME_VERSION_PATCH = 32;
        
        public const string CEF_API_HASH_UNIVERSAL = "ce9401699c6753553cba867b1f5c329f759d2c67";
        
        public const string CEF_API_HASH_PLATFORM_WIN = "e094f42b7a60d2c8c9bcb3db51907a3b42f51d04";
        public const string CEF_API_HASH_PLATFORM_MACOS = "6ce44bd7182aa7e9544f5ca33c310f2a096ab638";
        public const string CEF_API_HASH_PLATFORM_LINUX = "8e9886cd490aefc89283d65f5f7d104a51e2d289";
    }
}
